name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Log in to Azure Container Registry
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: grandeur.azurecr.io   
          username: ${{ secrets.ACR_USERNAME }} 
          password: ${{ secrets.ACR_PASSWORD }} 
          
      # - name: Build the Docker image
      #   run: docker build -t grandeur.azurecr.io/cicdtest:$(date)
      - name: Build and Push Docker Images
        run: |
          for dir in $(find . -mindepth 3 -maxdepth 3 -type f -name 'Dockerfile'); do
          image_name=$(dirname $dir | cut -d'/' -f3,4)
          docker build -t grandeur.azurecr.io/$image_name:${{ github.run_number }} $(dirname $dir)
          docker push grandeur.azurecr.io/$image_name:${{ github.run_number }}
          done
      # Replace <ACR_NAME> with your ACR name
      # - name: Push to Registry 
      #   run: docker push grandeur.azurecr.io/cicdtest:$(date) 

          
